# Инструкция к плагину
# bcheck.admin - полный доступ к плагину
# bcheck.use - разрешение к команде /check <никнейм>
# %suspect% - ник игрока которого проверяют
# %executor% - ник проверяющего

# Технические сообщения
no-permission: '&cУ вас недостаточно прав!'
only-player: '&cКоманду может использовать только игрок!'
not-online: '&cИгрок оффлайн!'
remaining: '&7Ваше &6здоровье &7восстановлено приятной игры!'

# Кол-во секунд, через которое будет появляться сообщения: check-sms-move-player
# 20 тиков = 1 секунда
# defautl: 1200 - 1 минута
delay-freeze-message: 1200

# Все СМС связаные с командой /check
check-sms: '&7Модератор &e%executor% &7вызывает вас на проверку.'
check-sms-off: '&7Проверка окончена.'

check-sms-move-player:
  - '&7Вы вызваны на проверку читов!'
  - '&7У вас есть 5 минут на то чтобы скинуть свой дискорд!'
  - '&7Комманда для связи /msg %executor%'

check-sms-moder-start: '&7Вы начали проверку игрока &e%suspect%'
check-sms-moder-stop: '&7Вы завершили проверку игрока &e%suspect%'

freeze-args: '&7Использование: &6/check <никнейм>'

# Сообщения из тайтлов
title-check-sms-start: '&cНе выходи с сервера!'
subtitle-check-sms-start: '&7У тебя &c10 минут, &7чтобы предоставить дискорд!'

title-check-sms-stop: '&aПроверка окончена!'
subtitle-check-sms-stop: '&7Всего доброго!'

# Настройки конфига "logs.yml"
logs:
  logs-false-sms: 'Данные об проверке, не были занесены в конфиг'
  add-logs-file: true

# Включение / Выключение воспроизведения звука взрыва тотема, в начале и конце проверки
# true - включено / false - выключено
sound-freeze:
  start: true
  stop: true

# Конфигурация команд, которые выполняются от имени консоли
commands:
  on-freeze-start:
  - "spawn %suspect%"
  on-freeze-stop:
  - "spawn %suspect%"

# Настройка эвентов, которые будут блокироваться при заморозке игрока
# true - выключено / false - выключено
settings-event:

  # Эвент, отвечающий за блокировку возможности передвижения игрока во время проверки
  PlayerMoveEvent: true

  # Эвент, отвечающий за блокировку взаимодействие с сундками и т.п
  PlayerInteractEvent: true

  # Эвент, отвечающий за блокировку возможности выбросить вещи из инветаря
  PlayerDropItemEvent: true

  # Эвент, отвечающий за блокироку получения дамага от игроков / мобов
  EntityDamageEvent: true

  # Эвент, отвечающий за блокировку возможности подбирать предметы
  EntityPickupItemEvent: true

  # Эвент, отвечающий за блокировку возможности наносить урон игрокам/мобам
  EntityDamageByEntityEvent: true

  # Эвент, отвечающий за блокировку возможности перемещать предметы в инвентаре
  InventoryClickEvent: true